server:
  port: 8056
access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
accessTokenExpirationMinutes: 5
refreshTokenExpirationDays: 30
accessTokenSecret: 12345
refreshTokenSecret: 54321
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/?authSource=${MONGODB_AUTH_DB}&readPreference=primary&appname=${MONGODB_APP}&directConnection=true&ssl=true
      database: ${MONGODB_DB}
logging:
  level:
    org.springframework.security: DEBUG
jms:
  configuration:
    base-url: "/api/v1"
#
#spring:
#  data:
#    profiles:
#      active: dev
#    mongodb:
#      database: iot
#      uri: mongodb://userAdmin:kZWQiOnRydWV9LHsiY29@prod.kathesama.com.ar:27017/?authSource=admin&readPreference=primary&appname=restfulapi&directConnection=true&ssl=true
##      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/?authSource=${MONGODB_AUTH_DB}&readPreference=primary&appname=${MONGODB_APP}&directConnection=true&ssl=true
##      uri: mongodb://mongoAdmin:mongoPass@localhost:27017/?authSource=admin&readPreference=primary&appname=restfulapi&directConnection=true&ssl=false

