ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"
MONGODB_USERNAME: "userAdmin"
MONGODB_PASSWORD: "kZWQiOnRydWV9LHsiY29"
MONGODB_HOST: "prod.kathesama.com.ar"
MONGODB_PORT: 27017
MONGODB_DB: "api-rest"
MONGODB_RS: "rs1"
MONGODB_APP: "rs1"
MONGODB_AUTH_DB: "admin"
